### ISSUE TITLE
Enhance error message

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1092]
Steps:

1. Go to Organization -> Cache Refresh
2. Immediately click either Update or Update&Validate Script

Expected: As a user I want to be taken to the problematic view/tab if the update fails.

Actual: The user sees 4 error messages with typos, but the necessary fields are not present on the shown tab. 
It can be confusing, so the best solution would be to take the user to the mentioned fields/tab. For better UX we should unify and implement this behavior. Also, please correct the typo everywhere in the code:
<img width="327" alt="typo1" src="https://user-images.githubusercontent.com/38302725/44071918-33c35aa0-9fcf-11e8-86be-9ff9013c005f.png">

**Comment by earezki** [comment]
This makes sens,
But, the issue is that we're updating every tab when we hit update (for all the views), means we can have validation errors in mixed tabs.
To test, remove the base dn in the Inum LDAP Server tab and hit update:
![image](https://user-images.githubusercontent.com/11857979/44159280-d5694600-a0ae-11e8-8678-e2f20b2d9abf.png)
This won't be an issue in the new api.
For now, I propose to only fix the typo (Good catch BTW, thx).

**Comment by earezki** [comment]
What we may do is to add an indication on the fields that are not valid:
![image](https://user-images.githubusercontent.com/11857979/44164648-85927b00-a0be-11e8-8fed-836992cfc68e.png)
But this would be an enhancement for another release.

**Comment by natt-tester** [comment]
@earezki, I see what you mean. The enhancement will be a most welcome change, but I guess we need more time to carefully plan it.

**Comment by natt-tester** [comment]
Confirmed, the typo is fixed.
