### ISSUE TITLE
Authentication graph improvement 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1196]
Right now, graph and data below graph is showing last 7 day activity. 
A customer suggested to include information of 'Total login' instead of "Last 7 days statistics" graph ( or, along with "Last 7 days statistics" [ red banner ]. 

Do you think it's possible? 
![protected_answer_4755_skewed_statistics_9-10-2018](https://user-images.githubusercontent.com/7156097/45299587-ad181000-b4d1-11e8-9772-7a5bfbdc666b.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46665339-71996000-cbbb-11e8-9b2e-3ba71ad05ae1.png)

**Comment by syntrydy** [comment]
@tcerise is it as you want it to be?
@mzico is that correct for you?

**Comment by tcerise** [comment]
Yes, that is very nice.   The 7 day graph is a good representation of the last week's success/failed login attempts.  The totals at the bottom should represent the totals since the system was started, or the last time the counters were reset to reflect the actual total numbers and not simply the weeks numbers shown in the graph.  It currently does show the sum totals, it is just that the graph itself is skewed by them.

Does that make sense?  Thanks.

**Comment by syntrydy** [comment]
@tcerise About this **The totals at the bottom should represent the totals since the system was started** i think we can summarized that to **The total 365 days(one year) authentication requests**

Right now we don't want to create a now entry in Ldap just to store the last system restart date. Also showing the last 365 days authentication days is a pretty decent amount of data.
Make sense?

**Comment by tcerise** [comment]
That sounds fine to me.  Thanks.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46732569-bf7a9a80-cc85-11e8-99be-75446159da2d.png)

**Comment by natt-tester** [comment]
@syntrydy, I think maybe we could improve it still by adding (s) to Total Successful Login and Total Failed Login:  **Total Successful Login(s)**.

**Comment by willow9886** [comment]
I would just make it plural by default: 

Logins

**Comment by tcerise** [comment]
@syntrydy, We have 3.1.5.4.Final in testing now, and while this new graph is visually improved, the behavior is still the same.  The following set of three screenshots shows that the graph continues to show the total request count.  Points 1, 2 and 3 show that the total count is still shown in the graph, although point 3 now has it shifted to an arbitrary day in the graph vs. simply keeping the count on the 7th day of the graph.  This is also shown in the yellow highlight for each graph, showing that the 365 and 7 day request totals are all the same for each graph.  

Each of the three sceenshots also tracks two days, 2/12/2019 and 2/14/2019.  It is clear to see in the second and third graphs that the totals go from 1 successful login each day, to zero in the third graph when the total count shifts to 2/16/2019.  

It seems that the total count is still not being dropped off the graph, and the last 7 days are not being counted separate from the total, 365 day count.  The backend counters need to be corrected and then reflected properly in the 7 day statistics on both the graph and the successful and failed login counters.

![graph still broke 3 1 5](https://user-images.githubusercontent.com/43142349/53091071-fd62b780-34de-11e9-9982-fcd7e0735696.png)
