### ISSUE TITLE
User registration has Test too tip field

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1214]
![image](https://user-images.githubusercontent.com/21104811/45526555-4195b180-b7f5-11e8-8dc9-c0474a71e897.png)

**Comment by natt-tester** [comment]
@sahiliamsso, @syntrydy, I've checked RC5 and there's no extra field:

<img width="783" alt="register" src="https://user-images.githubusercontent.com/38302725/45596497-074c3000-ba00-11e8-9227-f6d093cd1dd8.png">

**Comment by willow9886** [comment]
That means it was fixed :) tool tip field was not supposed to be there.

**Comment by natt-tester** [comment]
@willow9886 
- the admin creds are from the same browser and show up in oxTrust (Firefox)
- yes
- I don't think it's because of different functionalities, it's most likely because I saved the creds for the admin account during the login and they show up for the same fields across oxTrust
- only if they share the same machine

It's related to https://github.com/GluuFederation/oxTrust/issues/1139.
