### ISSUE TITLE
Add support for granular permission management

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1365]
# Description

- A **User** may have a set of **Roles** associated to him(example **John**)
- A Role can be assigned to a **User**, a roles is defined by a set of **Entities**(example **MANAGER**)
- An **Entity** is a manageable item from the application point of view(example **UMA SCOPE**), an Entity has set of actions applicable to it(example **VIEW**, **ADD**, **EDIT**, **REMOVE**)
- An Action is what a user can perform on a given **Entity** (**John can DELETE a UMA SCOPE**)
- Ability to add/edit/delete/view new role

**Comment by yurem** [comment]
In oxTrust from beginning we tried to cover all parts by rules. We used Drolls for this: https://github.com/GluuFederation/oxTrust/blob/version_3.0.3/server/src/main/resources/security.drl
In 3.1 we deprecated this since admin should have access to all permissions...

If customers is need this we can create CDI extension which will check permissions of specific method. We can add class/method anothations like:
@Role(value = [role1, role2], expression = "el_expression", etc..)
Via expression we can pass bean parameters to our extension method..

**Comment by nynymike** [comment]
Not a direction we want to go right now. If a customer needs a UX with less features, they can build their own with oxTrust API's.
