### ISSUE TITLE
Unified and externalize logo and favicon 

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1671]
Currently, the logo and favicon are packed into Gluu components( oxauth.war, identity.war, idp.war) and hardcode in public pages.

Each war containing the logo and eventually the favicon. This approach provides several disadvantages. The main issue with such an approach is that it is very difficult for customers to apply custom branding.

We need to define a single point where both the logo and favicon can change once and apply to all pages.

The solution I offer is to leverage the custom folder we have already.

Currently, if a file name **logo.png** is put in customer folder **/opt/gluu/jetty/identity/custom/static/img/** that logo will be use for all public pages.

We can  put default gluu logo and favicon in that folder during installation and change the code to read log from that folder.

**Comment by syntrydy** [comment]
@yuriyz @yurem what do you think about the solution proposed?

**Comment by yuriyz** [comment]
Lets make logo and favicon configurable. Since each app is independent I guess icon and favicon will go with each app (we don't want absent icon for oxauth if oxtrust is not installed on same machine). From other side if we make it configurable then changing/unifying it to some custom icon would be trivial (e.g. point all apps to same location of icon/favicon).
