### ISSUE TITLE
Show status of Cache Refresh

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#170]
1) Add a counter showing current CR's state/progress to its configuration page. States like "idling due to errors in config"/"awaiting next iteration"/"pulling"/"updating inum db"/"updating user entries" and, perhaps, a rough estimation of current progress/estimated time of completion.
2) Remove a web UI user's ability to save a CR configuration with a double mappings in it. Currently CR allows mappings like this:

src_attr1 -> dst_attr1
src_attr2 -> dst_attr2
src_attr3 -> dst_attr2

I.e. 2 different source attributes mapped to a single internal one. This doesn't produce an error neither during saving the configuration, nor during actual updates of internal db. I didn't investigate which one of two value will be assigned to the target attributes, but it just doesn't feel right. I don't think there is a reason to allow something like that, and that can potentially lead to unpredictable results, in case of long list of mappings (user can miss the fact he already has mapped something to some attribute before, and map another one to it again). Mb even better to make oxtrust's backend reject such configuration, not just web UI (i.e. so that a user couldn't edit config in LDAP directly and add something like that). That would eliminate any possible issues that can stem from such ambiguous mapping.

**Comment by nynymike** [comment]
2) Remove a web UI user's ability to save a CR configuration with a double mappings in it. Currently CR allows mappings like this:

src_attr1 -> dst_attr1
src_attr2 -> dst_attr2
src_attr3 -> dst_attr2
If this isn't hurting anything, I don't think we need to add the feature:

I.e. 2 different source attributes mapped to a single internal one. This doesn't produce an error neither during saving the configuration, nor during actual updates of internal db. I didn't investigate which one of two value will be assigned to the target attributes, but it just doesn't feel right. I don't think there is a reason to allow something like that, and that can potentially lead to unpredictable results, in case of long list of mappings (user can miss the fact he already has mapped something to some attribute before, and map another one to it again). Mb even better to make oxtrust's backend reject such configuration, not just web UI (i.e. so that a user couldn't edit config in LDAP directly and add something like that). That would eliminate any possible issues that can stem from such ambiguous mapping.

**Comment by shekhar16** [comment]
@yurem @nynymike how can i create 2 instance of openldap in windows dev setup to test this issue?

**Comment by nynymike** [comment]
Use two VM's. This should be doable with VMPlayer. You don't need much RAM for just a test openldap. Then just make sure your local windows host file is up-to-date.

**Comment by shekhar16** [comment]
Duplicate key attributes will not allowed.
