### ISSUE TITLE
Log viewing from the UI allows to display of any sensitive file

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1867]
## Describe the issue
Log viewing from the UI allows displaying of any sensitive file within the container that's accessible by jetty
## Steps To Reproduce
1. Go to 'Log view configurable'
2. Add new template like this  '/etc/certs/*.*'
3. Save and check log viewer menu '....'
4. See sensible file are listed

## Expected behavior
We have to display only file ending with *.log

## Actual behavior
Even sensible files like private key are viewable from GUI

## Screenshots
![image](https://user-images.githubusercontent.com/7513418/67837395-397afd00-faef-11e9-918d-6fb267074eb4.png)

## Desktop (please complete the following information):
 - OS: All
 - Gluu version: All

**Comment by yurem** [comment]
We need to lint this with jetty log files only

**Comment by cybersei** [comment]
As a potential solution you can either allow templates to be modified only on the OS via file or hard-code them to inlcude log directories only. Even in that case path and link traversing should be forbidden to prevent exploits that link sensitive files to be displayed.

Generally while a helpful feature for Development environments, log viewing via the GUI is not safe in Production systems and there should be a way to disable it on the OS so no OS files are exposed via the web admin interface. Even log files can themselves with elevated logging levels DO disclose sensitive information via the GUI (such as keys, secrets, etc.), which is why being able to turn off log viewing from the OS I believe is important.

**Comment by nynymike** [comment]
There should be a whitelist of files that can be viewed. 

Also, I agree that we should add a feature to oxTrust JSON properties to enable/disable this feature. In practice, it's needed only by low-end deployments.

**Comment by cybersei** [comment]
Thanks Mike. From a security perspective however adding a setting in
oxTrust JSON still makes the feature available from a web browser and the
issue will persist.

The mechanism to turn on the feature should be independent of the web
interface and can be reused for any Production security hardening flags.

I do understand it is trickier on containers because it requires shared
persistent storage or image modification.

**Comment by nynymike** [comment]
It's a good point. Maybe we should just remove this feature.
