### ISSUE TITLE
Remove Activate/Deactivate Buttons from Manage Authentication

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#190]
Both these Activate / Deactivate buttons should be Removed.

![image](https://cloud.githubusercontent.com/assets/3717101/12306253/6c382dac-b9fe-11e5-869f-bbe7983ffcd5.png)

![image](https://cloud.githubusercontent.com/assets/3717101/12306258/76471272-b9fe-11e5-8186-12199775b4bd.png)

To clarify, LDAP authentication having an "Enabled" checkbox is sufficient. If it is not enabled, this authentication mechanism should not be available.

**Comment by willow9886** [comment]
@yurem can you comment on this?

**Comment by yurem** [comment]
I would like to keep "Activate/Deactivate button" and just hide Enabled from LDAP setting.

I think so, because:
1) After Deactivate  and click Update we completely remove setting. oxAuth can detect this.
2) When we click Enable checkbox we still need to save this form to notify oxAuth to reload setting
3)  it's requires less changes: just set in bean Enable=True after clicking Activate and hide this checkbox.

The point 1 is the main point here. This allows completely remove AD LDAP setting and password from LDAP.

**Comment by shekhar16** [comment]
Hide the enabled checkbox from ldap setting and set Enabled property i.e. ldapconfig.enabled = true on click of activate button.
let me know if any change needed.

**Comment by nynymike** [comment]
yes, that's fine too...

**Comment by yurem** [comment]
@shekhar16 can you take look on changes which you applied to  server/src/main/webapp/resources/ox/ldapConfig.xhtml

It facelet, reusable component. We need to hide this field in another way... In this faclelet there is property "displayEnable". Hence you can find where we define this component. It will be somethig like this:
<ox:ldapConfig .... displayEnable="false" ... />

**Comment by yurem** [comment]
We can retest it an close
