### ISSUE TITLE
Passport Config: field mapping dropdown

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2027]
In the oxTrust passport configuration field mapping section, currently admins have to go to the docs, copy the mapping text, and enter into passport mapping config field. It would be better if there was a dropdown with all known values with editable fields.

**Comment by kdhttps** [comment]
same facility needed for `Passport.js strategy: *` field also in same passport config page

**Comment by jgomer2001** [comment]
It is not clear the approach used to solve this issue. In latest available 4.2.2 I noticed several things:

- Fields "Mapping" and "Passport.js strategy" are not mandatory anymore in the UI, why? they have to be required
- Known values for mapping can be infered from files found at `/opt/gluu/node/passport/server/mappings`. If I start typing things like "apple", "facebook", etc. I get no suggestions. If "open" is typed, the suggestion is "opendidconnect-default" which has a typo
- Regarding the strategy field, I get the exact same suggestions of mapping. In passport documentation known values can be found

Other observations:
- I think the intention of the issue was showing  drop-downs with the possibility to enter text freely which I find more convenient than the predictive style
- In 4.2.1 and earlier, when a value is selected for "type"  (except for the case of `oauth`),  mapping and the strategy fields are already filled automatically. We lost that functionality here....

**Comment by syntrydy** [comment]
Fixed.
