### ISSUE TITLE
Setting custom acr-value for IDP-Initiated Flow

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/oxTrust#2051]
User should be able to setup custom acr value for idp-initiated so that user can use other custom scripts then `passport-saml`.

Maybe we can set flags on idp-initiated custom scripts?

**Comment by jgomer2001** [comment]
@syntrydy can you change the form so that the highlighted field in the image render as a list where the user can pick from the available enabled scripts? passport_saml should be the default selected item (even if that's script is not enabled)

![Screenshot from 2021-01-27 11-22-08](https://user-images.githubusercontent.com/5444180/106021350-b4d0b300-6092-11eb-84d3-3ec943b2f393.png)

**Comment by christian-hawk** [comment]
@syntrydy can you please update us?

**Comment by syntrydy** [comment]
Fixed
