### ISSUE TITLE
oxTrust feature "Profile" 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#29]
oxTrust feature: "Profile" is showing read-only report. It is not allowing user to change password / add or modify any attribute. 

Though there are couple of standard ways to add / modify attributes (Gluu Server admin can add/remove attributes with another feature ) and change password ( self-signed password reset feature ) so I am exactly not sure if we *really* need to enable *this* feature. May be we need to make some decision? 

Screenshot attached. 

![dashboard](https://cloud.githubusercontent.com/assets/7156097/5916361/f06f7ae6-a5d5-11e4-8420-f09f9a2c23f9.png)

![read_only](https://cloud.githubusercontent.com/assets/7156097/5916365/f7dcfa06-a5d5-11e4-88cd-94c75f25d9c7.png)

**Comment by rystraum** [comment]
I've decided to look into this further.

The profile page is rendered using [viewProfile.xhtml](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/webapp/profile/person/viewProfile.xhtml) which suggests that it should already be editable as indicated in line 67 (userCanEdit? ' edit' : 'view') if isUserCanEdit() returns true.

isUserCanEdit() can be found in [GluuAttribute.java](https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/GluuAttribute.java) which calls allowEditBy(GluuUserRole.USER) which checks if editType (the LDAP enum) contains GluuUserRole.USER.

[GluuUserRole.containsRole()](https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/GluuUserRole.java) does this in line 73-75: if (role.equals(roles[i])) { return true; }

I tried looking for how GluuUserRole implements .equals() but this is probably the one inherited from Object. I think this is where the problem lies. Object.equals() only does a pointer check, where what we wanted to compare was the values of the role. A possible solution is overriding .equals() for GluuUserRole.

	public boolean equals(GluuUserRole role) {
		return (this.getValue() == role.getValue())
	}

I don't have a proper build environment for Java in my computer so perhaps you might test this solution?

**Comment by RubenatorX** [comment]
Any progress on this front? I really need users to be able to edit some of their information.

**Comment by yurem** [comment]
We will take a look on this issue after 2.1 release

**Comment by RubenatorX** [comment]
So, in the meantime... the only way for users to update their own email address is to email me?

**Comment by nynymike** [comment]
Gluu supports the SCIM interface if you want to have another application make a call to update the attribute. You can also use LDAP. The primary purpose of the gluu server is central authentication / authorization. While we do have some identity management features, these features take a back seat in priority to access management. Self-service is definitely one of those IDM features that we'd like to see develop, but don't have the highest priority.

**Comment by rystraum** [comment]
@RubenatorX We've found a fix via changing LDAP attributes.
You need to change the attribute gluuOrgProfileMgt from disabled to enabled of the gluuAppliance dn.
Here's what worked for us, just modify to your setup.

      root# /opt/opendj/bin/ldapmodify -h localhost -p 1389 -D 'cn=Directory Manager' -w 'password'
      dn: inum=@!<inum of gluu appliance>,ou=appliances,o=gluu
      changeType: modify
      replace: gluuOrgProfileMgt
      gluuOrgProfileMgt: enabled

You can get the inum of your gluu appliance in /opt/tomcat/conf/oxauth-ldap.properties
the line that says configurationEntryDN should have the inum.

Once that has been enabled, the attribute settings under Configuration > Attributes > Edit Type should now take effect.

Hope that helps.

**Comment by rystraum** [comment]
@RubenatorX I've created a pull request that includes the setting under Configuration > Organization Configuration. This pull request and the LDAP workaround does the same thing.

**Comment by RubenatorX** [comment]
Oh great thank you! Good work. My users will be grateful.

**Comment by rystraum** [comment]
@yurem I think this issue can be closed now.

**Comment by yurem** [comment]
Thank you for your research and help.
