### ISSUE TITLE
oxTrust UMA service must provide ability to set custom connection manager

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#303]
Reported by https://support.gluu.org/integrations/resteasy-errors-in-logs-3004
org.gluu.oxtrust.service.UmaAuthenticationService uses protection service that uses defalut BasicClientConnManager.

https://github.com/GluuFederation/oxTrust/blob/fcce976ca6c8c94b2405e66aae23a9bb6727a600/server/src/main/java/org/gluu/oxtrust/service/UmaProtectionService.java#L95

It seems we need to make it configurable in order to handle more requests during high load.

Please check this method where it's possible to specify ClientExecutor https://github.com/GluuFederation/oxAuth/blob/master/Client/src/main/java/org/xdi/oxauth/client/uma/UmaClientFactory.java#L66-66

**Comment by uboznikov** [comment]
Was able to re-create this issue on multi-threaded unit tests. See passed tests after fix. The multi-threaded tests used 15 invocations sharing 5 threads each.

[GroupFiltersMainTests](https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/java/gluu/scim/client/GroupFiltersMainTests.java)

![multithreaded-tests-passed](https://cloud.githubusercontent.com/assets/16329085/17658329/7ce3ad7c-62fd-11e6-8540-138dd6d15e70.png)

**Comment by yurem** [comment]
Fix looks fine for me.

I only think that adding more properties for specific part will add not needed complexity.

```
    "rptConnectionPoolUseConnectionPooling":false,
    "rptConnectionPoolMaxTotal":200,
    "rptConnectionPoolDefaultMaxPerRoute":20,
    "rptConnectionPoolValidateAfterInactivity":10,  // In seconds; will be converted to millis
    "rptConnectionPoolCustomKeepAliveTimeout":5,  // In seconds; will be converted to millis
```

What do you think about removing prefix rpt to allow us reuse same properties in the future?

Also we can move connection pool specific [code](https://github.com/GluuFederation/oxTrust/blob/5a75cb389a926592fc9f0158876f73f732e2e570/server/src/main/java/org/gluu/oxtrust/service/UmaProtectionService.java#L119) into separate class NetworkService to allow reuse shared connection pool instance. Also wecan moe this service into oxService to allow reuse it in oxAuth/oxTrust and other projects which uses oxService library.

**Comment by uboznikov** [comment]
Thank you for the comments.

For the properties these are the minimum needed by [PoolingHttpClientConnectionManager](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/index.html?org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html).

I also added comment for client:
[See JavaDoc](https://github.com/GluuFederation/oxTrust/blob/5a75cb389a926592fc9f0158876f73f732e2e570/server/src/main/java/org/gluu/oxtrust/service/UmaProtectionService.java#L115-L116)

I will check if this can be moved to a generic library since right now the parameters are configured via oxTrust GUI and stored in LDAP under oxTrust config.
