### ISSUE TITLE
Review oxTrust InumService 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#323]
![mysqlerror](https://cloud.githubusercontent.com/assets/7156097/17554800/4c078180-5ed2-11e6-8e06-45f4e3a7041e.png)

**Comment by yurem** [comment]
It looks like we still trying to use MySQL to get unique inum. We need to open issue to review oxTrust InumService. We need to do search in LDAP instead of MySQL.
Also I see that we have different InumService implementation in oxAuth and oxTrust. In oxAuth application calls external script to allow use custom idGenerator. In oxTrust there is no such code. We need to move generic part to oxCore to allow reuse same code in both projects.

**Comment by nynymike** [comment]
yes, I can't even remember using MySQL for this...

**Comment by shekhar16** [comment]
I checked the code and found that this is a check whether this new created inum is already exist or not in available DBs i.e ldap and connecting other DBs.

**Comment by nynymike** [comment]
I think this is a duplicate issue: https://github.com/GluuFederation/oxAuth/issues/484
