### ISSUE TITLE
RHEL 6.7: High traffic on SCIM endpoints results in "client denied by server configuration" by httpd

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxTrust#362]
![client-denied-by-server-conf](https://cloud.githubusercontent.com/assets/16329085/18876305/ad109f9e-84fb-11e6-8043-cab28cdbe09f.png)

The suggested fix is here:
[Client denied by server configuration](http://wiki.apache.org/httpd/ClientDeniedByServerConfiguration)

Configuration/Installer would need to be looked into.

**Comment by yurem** [comment]
@adrian-gluu , @ganesh-at-wiw As far as I remember we enable Anti-DOS modules in Ubuntu 14.04 only.
I offer to uninstall these modules from Ubuntu 14.04 chroot to conform all other chroot.
And write article for CE documentation about manual enabling Anti-DOS modules in CE.

Without disabling this in Ubuntu 14.04 we always will get support tickets about this issue. Because admin don't know that we enable these modules in this chroot by default.

**Comment by ganesh-at-wiw** [comment]
Yes, that's better Idea @yuriyz .
I can arrange this.

**Comment by yurem** [comment]
Thanks @ganesh-at-wiw

**Comment by alvesadrian** [comment]
i think i applied to all the chroots

**Comment by adrian-gluu** [comment]
i think i applied this into all of the chroots

**Comment by ganesh-at-wiw** [comment]
For CentOS 6.x, I've disabled anti-DoS stuff. This is my commit: https://github.com/GluuFederation/community-edition-setup/commit/45515f876043bc5b228b795974968d6006cbf319#diff-39e94c8e83301ceaa9dcf62c2bcf5564

Checking for other platforms as well.

**Comment by ganesh-at-wiw** [comment]
For CentOS 6.x, I've disabled anti-DoS stuff. This is my commit: https://github.com/GluuFederation/community-edition-setup/commit/45515f876043bc5b228b795974968d6006cbf319#diff-39e94c8e83301ceaa9dcf62c2bcf5564

Checking for other platforms as well.

**Comment by ganesh-at-wiw** [comment]
CentOS 7.x is clean.

**Comment by ganesh-at-wiw** [comment]
Ubuntu 14.04  is clean.

**Comment by ganesh-at-wiw** [comment]
Ubuntu 16.04 is also clean.
