### ISSUE TITLE
Confirmation email upon successful registration

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#43]
It would be nice if oxTrust / Registration could send a confirmation email after successful registration to newly registered user. 

Requesting this feature for Gluu Server Version-2.2

**Comment by willow9886** [comment]
@mzico Hard coding this specific use case only scratches the surface.. wouldn't it be better to have a 'notifications configuration' section that allowed Gluu Server admins to configure notifications?

**Comment by nynymike** [comment]
There is a post registration interception script where you could add this type of functionality. I'm not convinced there is enough demand for this...

**Comment by RubenatorX** [comment]
In my opinion, email confirmation is a basic and essential part of registration of an unknown user. I certainly don't want to be sending emails (like notifications and newsletters) to random emails owned by people that did not sign-up themselves.
@nynymike, it is one thing to script an email to be sent out on registration, its another thing to accept the incoming link to mark the email as valid.

**Comment by nynymike** [comment]
The Gluu Server is primarily an access management platform (i.e. central authn / authz). There are many requests for handy IDM features, There is already an SMTP component in Seam. So if you want to submit the code, or post a bounty to write this feature, you can help expedite it! Otherwise, we need to prioritize features that align with our business model.
