### ISSUE TITLE
OpenLDAP doesnt start after adding custom attribute

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/oxTrust#483]
followed document, which was taken from Yurem ticket response. works well in Ubuntu. same commands doesn't start ldap in centos.

See support ticket: https://support.gluu.org/single-sign-on/3730/unable-to-start-solserver-after-applying-custom-attribute

**Comment by yurem** [comment]
In CE 3.0.0 we not uses /opt/symas/etc/openldap/slapd.d
But there are steps which allows to re-generate /opt/symas/etc/openldap/slapd.d:

    backup /opt/symas/etc/openldap/slapd.d
    remove /opt/symas/etc/openldap/slapd.d
    create empty dir /opt/symas/etc/openldap/slapd.d
    /opt/symas/bin/slaptest -f /opt/symas/etc/openldap/slapd.conf -F /opt/symas/etc/openldap/slapd.d

**Comment by nikohd** [comment]
I still can't create custom attributes in centos.

**Comment by willow9886** [comment]
@nikohd please open a support ticket on https://support.gluu.org

Include all relevant logs, and steps to reproduce.

Thanks!

**Comment by yurem** [comment]
yes, we can close this ticket because in final 3.0.1 there is no folder "/opt/symas/etc/openldap/slapd.d" which we need to update. To add new attribute we can edit for example "/opt/gluu-server-3.0.1/opt/gluu/schema/openldap/custom.schema" and just do solserver restart.

After editing schema file run next command to make sure that your changes are right:
```
GLUU.root@u144:~# /opt/symas/bin/slaptest -f /opt/symas/etc/openldap/slapd.conf
config file testing succeeded
```
