### ISSUE TITLE
Make sure validated id_token acr claim equals specified oxTrust authn method

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#513]
How to authenticate is controlled via the browser (i.e. a GET request to the `authorize` endpoint). So nothing stops a user from using a different type of authentication just by changing the value of the authorization endpoint URL.  However, once authenticated, the validated `id_token` can be trusted.  Therefore, when oxTrust creates an application session, if an authn method is specified for oxTrust (see screenshot below), the `id_token` acr claim should match. 

![image](https://cloud.githubusercontent.com/assets/3717101/24564198/b1a40580-1616-11e7-84fc-1b97d518b637.png)

Ideally, if the authn method was not matching, oxTrust would redirect back to oxAuth with authorization request params `prompt=login` and 'acr_values=(specified)`

**Comment by yurem** [comment]
oxTrust validates authentication method which oxAuth used for authentication already:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/Authenticator.java#L485

@shekhar16 can you try to change in authorization request acr_values parameter?

**Comment by shekhar16** [comment]
yes i agree ,but as per Mike we had to redirect to oxauth/login with params like nonce + acr values

**Comment by yurem** [comment]
I think we should not add property to explicitly specify https://{host}/oxauth/login

Right now oxTrust has property <b>'oxAuthIssuer'</b>. At user login it request metadata from specified server. And uses <b>'authorization_endpoint'</b> in order to send request.

There is only one missing part. oxTrust should verify if specified issuer really issued id_token for oxTrust. It can check ISSUER claim of id_token

**Comment by nynymike** [comment]
Yes, it should verify both the `issuer` and the `acr` in the id_token.

**Comment by shekhar16** [comment]
Fixed.

**Comment by nynymike** [comment]
This fix needs to be applied to 3.0.2
