### ISSUE TITLE
Update login page design.

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#596]
![image](https://user-images.githubusercontent.com/15937500/27516248-db7a0002-59d3-11e7-8ba7-be6f6decb3ef.png)

**Comment by willow9886** [comment]
@shekhar16 just want to confirm this is the design used when passport is enabled and in use as the login strategy?

**Comment by qbert2k** [comment]
@shekhar16  @willow9886 

According to specs the Client has metadata for Terms Of Service and Privacy Policy links:

http://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata

If possible please display them in the UI when present, for example, in old code:

```
<h:panelGroup layout="block" rendered='#{!empty client.policyUri}'>
    <p>
        <h:outputText value="#{msgs['common.agreePolicy']}" />
        <a target="_blank" href='#{client.policyUri}'>
            <h:outputText value="#{msgs['common.privacyPolicy']}" />
        </a>
    </p>
</h:panelGroup>
<h:panelGroup layout="block" rendered='#{!empty client.tosUri}'>
    <p>
        <h:outputText value="#{msgs['common.pleaseReadTheTos']}" />
        <a target="_blank" href='#{client.tosUri}'>
            <h:outputText value="#{msgs['common.termsOfService']}" />
        </a>
    </p>
</h:panelGroup>
```

Since those links were removed, there are interop test failing right now:

https://ox.gluu.org/jenkins/job/oxAuth/2123/testReport/org.xdi.oxauth.interop/DisplaysPolicyUriInLoginPage/displaysPolicyUrlInLoginPage/
https://github.com/GluuFederation/oxAuth/blob/master/Client/src/test/java/org/xdi/oxauth/interop/DisplaysPolicyUriInLoginPage.java

**Comment by shekhar16** [comment]
Login page when passport is disabled : 
![image](https://user-images.githubusercontent.com/15937500/27769647-4fd41e7e-5f4c-11e7-970c-d32c1ab04fc4.png)


Login Page after passport enabled:

![image](https://user-images.githubusercontent.com/15937500/27769657-98ca1638-5f4c-11e7-8b0a-abb64b26063c.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by willow9886** [comment]
@shekhar16 we still need to add privacy policy and terms of service links here.

**Comment by willow9886** [comment]
@shekhar16 also note that when passport is enabled, we should only show the social media icons that have been enabled. 

So if only facebook login is enabled, we only show facebook button on the login page. 

If facebook and twitter login are enabled, we show fb and twitter buttons. 

Does that make sense?

**Comment by yurem** [comment]
My 2 cents: https://github.com/GluuFederation/oxAuth/commit/71e4d02475c32f995454517f7f142df13ddf2231

I've restored logo section.
