### ISSUE TITLE
UI locale Support for oxTrust

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#597]
I'm not sure if this is a bug or a gap in the docs:

[Issue 4240](https://support.gluu.org/other/4240/ui_locales-does-not-work-correctly/)

```
Hi everyone, I add two new languages file to oxAuth.war with names 
messages_az.properties and messages_ru.properties. After adding these 
file I also add these new languages to uiLocalesSupported section from 
oxTrust admin GUI. After all these I restart gluu server. But when I set 
ui_locales parameters with authorization url it did not change ui languages. 
shows only english. But when set ui_locales=es it  works normally even I 
deleted this lang from settings.
```

**Comment by jschristie** [comment]
@nynymike: you mean to say this is a bug as in bug or its a gap/bug in docs? Because i dont see any gaps in docs. May be an extra pair of eyes should be able to point me the right direction.

**Comment by GuillaumeSmaha** [comment]
@nynymike I can reproduce this bug with version 3.0.2.
If I updated the file `messages_es.properties` in the war file `oxauth.war`, my translation will work correctly.

Do you provide a directory in `/opt/gluu/jetty/oxauth` to overwrite these properties files ? (instead of directly edit the war file)

**Comment by GuillaumeSmaha** [comment]
@nynymike I think I found why it doesn't work on 3.0.2.
I check files in `oxauth.war` and it seems that the files matches the version 3.0.1 instead of 3.0.2.
For example, I exactly have this file : https://github.com/GluuFederation/oxAuth/blob/v3.0.1/Server/src/main/webapp/WEB-INF/faces-config.xml

I installed gluu 3.0.2 with the rpm package for centos 7.

**Comment by worm333** [comment]
@GuillaumeSmaha right, in order to add new locales you need to add `messages_[locale].properties` to [resource](https://github.com/GluuFederation/oxAuth/tree/v3.0.1/Server/src/main/resources) folder and add language code as `supported-locale` to the [faces-config.xml](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/webapp/WEB-INF/faces-config.xml#L9).

Modifying `uiLocalesSupported` section from oxTrust does not seem to affect [faces-config.xml](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/webapp/WEB-INF/faces-config.xml). Probably we should add this feature.

**Comment by GuillaumeSmaha** [comment]
@worm333 Can you check the build for the RPM file https://repo.gluu.org/centos/7/gluu-server-3.0.2-1-1.centos7.x86_64.rpm to verify if the oxauth war is updated or still at version 3.0.1 ?

**Comment by worm333** [comment]
@GuillaumeSmaha I've checked the build it uses `3.0.2` version.

**Comment by GuillaumeSmaha** [comment]
@worm333 Thanks.
I also check and ` META-INF/maven/org.xdi/oxauth-server/pom.xml` contains `<version>3.0.2</version>`.
But my issue was a mismatched between war file and github (tag `3.0.2`) for the file https://github.com/GluuFederation/oxAuth/blob/3.0.2/Server/src/main/webapp/WEB-INF/faces-config.xml

But don't worry about it, I updated my ansible to update face-config.xml for the missing language.

**Comment by GuillaumeSmaha** [comment]
@worm333 I found another example that oxauth contains the file from 3.0.1.

I got an error after restart when I call `.well-known/openid-configuration`

```
2017-08-03 17:49:56,006 ERROR [qtp1395089624-15] [org.xdi.oxauth.servlet.OpenIdConfiguration$1] (OpenIdConfiguration.java:352) - null
java.lang.NullPointerException: null
	at org.xdi.oxauth.service.external.ExternalAuthenticationService.getCustomScriptConfigurationsMap(ExternalAuthenticationService.java:386) ~[classes/:?]
	at org.xdi.oxauth.service.external.ExternalAuthenticationService.getAcrValuesList(ExternalAuthenticationService.java:393) ~[classes/:?]
```

If I check the file `OpenIdConfiguration.java` on Github for both version 3.0.1 and 3.02 :

- https://github.com/GluuFederation/oxAuth/blob/v3.0.1/Server/src/main/java/org/xdi/oxauth/servlet/OpenIdConfiguration.java#L352

- https://github.com/GluuFederation/oxAuth/blob/3.0.2/Server/src/main/java/org/xdi/oxauth/servlet/OpenIdConfiguration.java#L352

As you can see, the version 3.0.1 matches with the call to `LOG.error(e.getMessage(), e);`

**Comment by GuillaumeSmaha** [comment]
@worm333 Apparently, the branch/tag `3.0.2` is not the same than `version_3.0.2`. Could you delete this branch `3.0.2` to avoid future confusion when somebody tries to explore the code of this version ?

**Comment by worm333** [comment]
@GuillaumeSmaha the branch 3.02 was removed from oxTrust. Hope it will help to avoid the confusion in future.
