### ISSUE TITLE
Wrong error message for authN failure

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#632]
Wrong credential is showing 'Incorrect email or password' though primary_key is 'Username' / 'UID'. 
![screenshot_15](https://user-images.githubusercontent.com/7156097/28791833-4dd2088a-75f3-11e7-96aa-aa812cc2cbc5.png)

Versions: All 3.x including 3.1

**Comment by mzico** [comment]
workaround: 

 - Un-war oxauth.war
 - Change value of 'login.errorMessage' attribute inside messages_en.properties
 - Re-war oxauth.war

**Comment by arsenb** [comment]
This is not the preferred method of dealing with this kind of modification because every update of the GLUU would be overwriting the change.
As documentation states a more permanent solution is placing the files in /opt/gluu/jetty/oxauth/custom/pages/..... 
We should find the reason why that is not working

**Comment by mzico** [comment]
@arsenb : The method I shared won't override the changes as it's inside war file. However... I agree that...this modification should be much simpler like others in /custom/pages/ type.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxAuth/commit/66bb8594f4db9f14f037f1f30eb63e3c0a5a6f41

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/28841669-9525d100-7718-11e7-9f03-235bd087dc50.png)
