### ISSUE TITLE
Bad error message on search with no values

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#652]
When I hit "search" on the "Manage People" page, with no value,  I got a weird error.

This is not a user friendly message

![image](https://user-images.githubusercontent.com/3717101/29254018-52cdf5d4-8051-11e7-8495-bc990cf72457.png)

An error message should display saying something to the effect of "2 characters are required to search people"

**Comment by jschristie** [comment]
![image](https://user-images.githubusercontent.com/23150138/29274478-a83675f8-8125-11e7-9f32-4ff001756342.png)

after searching with 1 character, i get a message which is great, but after entering two characters, i see "x" after search button

**Comment by yurem** [comment]
It's not one dialog issue. It's normal JSF 2.2 behavior to use clientId to show problematic field.
It's JSF 2.2 pattern.
javax.faces.validator.BeanValidator.MESSAGE={1}: {0}

Instead of clientId you can add label attribute to input field. JSF will use it instead of clientId in this case.

Also we can change pattern to:
javax.faces.validator.BeanValidator.MESSAGE={0}

You can add here custom JSF messages files:
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/webapp/WEB-INF/faces-config.xml#L19

**Comment by sahiliamsso** [comment]
Similar error message on Attribute screen
![image](https://user-images.githubusercontent.com/21104811/29347694-ff66c26a-823d-11e7-8658-27c8421971a8.png)
