### ISSUE TITLE
Remove Authorized Groups From Client Configuration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#68]
![image](https://cloud.githubusercontent.com/assets/3717101/7380975/edd70cea-edc4-11e4-9580-6fa920c8e9d9.png)

This feature should be removed.

**Comment by yurem** [comment]
Fixed

**Comment by yurem** [comment]
I reopened this issue because we uses oxAuthClientUserGroup client atribute in Client entry.
If we really need it in oxAuth we need to revert back 2 commits:
https://github.com/GluuFederation/community-edition-setup/commit/a00f84a8e00cadb050c7c8d8783e604118d3a03d
https://github.com/GluuFederation/oxTrust/commit/614a9b9ff0d8b7058774c1dd9330db7881a47baa

Javier, can you give advice about this attribute?

**Comment by willow9886** [comment]
@yurem is this still an issue in 2.4

**Comment by willow9886** [comment]
@qbert2k can you comment on this? See Yura's comment above..

**Comment by yurem** [comment]
I believe @qbert2k  can fix this

**Comment by willow9886** [comment]
@qbert2k can you comment on this?

**Comment by willow9886** [comment]
@shekhar16 reports that this has been resolved.
