### ISSUE TITLE
Federation SP not available

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#740]
Package: gluu-server-3.1.1.x86_64 1-1.beta3.centos6
Steps to reproduce: 
1. Add federation TR 
2. Select `Metadata Location: Federation`
There is no list of `entityID`  to choose from
![federation-error](https://user-images.githubusercontent.com/7703245/31050079-875da5a6-a662-11e7-8d49-638dfc95e235.png)

**Comment by zamilskhan** [comment]
This is how it should look
![federation-example](https://user-images.githubusercontent.com/7703245/31050364-0f7284fa-a66a-11e7-9382-afd622f53c1e.png)

**Comment by yurem** [comment]
I've fixed iCheck issue. Please, recheck it in next beta build again.

**Comment by yurem** [comment]
Fixed

**Comment by sahiliamsso** [comment]
Issue is still not fixed in fresh Beta build. I have to click "Add" button to get "Federation" option displayed.
![image](https://user-images.githubusercontent.com/21104811/31121506-17dccec8-a856-11e7-9b74-30c50a1079dc.png)

Created "Federation" TR
![image](https://user-images.githubusercontent.com/21104811/31121556-4b3f99f8-a856-11e7-835b-834dc475a0cd.png)

But it still show as type "Site"
![image](https://user-images.githubusercontent.com/21104811/31121589-7a623dc6-a856-11e7-8bd2-c7709c989043.png)

**Comment by yurem** [comment]
Fixed!
