### ISSUE TITLE
Mail Sent from Gluu Server is in text format

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#746]
Ticket: https://support.gluu.org/customization/4605/email-formatting/
The email sent from the Gluu Server is sent in "plain text" format. If this not a bug, please close issue. 

I tested the email format with mailtrap.io and found that the mail is available in plain text format only. Please see the following screenshot from mailtrap.io.
![mail-type](https://user-images.githubusercontent.com/7703245/31306653-5a468792-ab4c-11e7-8691-55157bff53b7.png)

**Comment by yurem** [comment]
We need to use XHTML to render messages in Mail service.

**Comment by yurem** [comment]
Improved next point in mail service:
1. Use one service 2 send messages by e-mail instead of 2 old utilities.
2. Send messages in plain and HTML format.
3. Internationalization.

There is one issue which I planned to implement but due to Richfaces issues I open separate issues for 3.2.0:
1. Repalces Richfaces with JSF2 and other JSF frameworks #768
2. Try to use JSF2 as mail templates #769

**Comment by yurem** [comment]
@willow9886 @zamilskhan can you update [oxtrust_en.properties](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/resources/oxtrust_en.properties#L865) properties "mail.verify.message.html.body", "mail.reset.found.message.html.body", "mail.reset.not_found.message.html.body", "mail.trust.released.attribute.html", "mail.trust.released.name.html" These are HTML representation of messages
