### ISSUE TITLE
Cover oxTrust API by tests

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#786]

**Comment by dmogn** [comment]
Integration test application repo:

https://github.com/GluuFederation/oxtrust-api-test

**Comment by yurem** [comment]
From my point of view we need to implement solution similar to oxauth-client. We need to do this because:

1. We need oxtrust-client as reference implementation for customers
2. Jekins automatically will execute tests during build time.
3. Server/Client/Tests will be joined by java code. Once someone change Client he need to update test. With separate project we periodically can get out of sync.

**Comment by dmogn** [comment]
oxtrust-api-test - moved to oxTrust/client.
oxTrust/model library - created.

**Comment by dnorthup-ums** [comment]
Why not using something like PhantomJS, which is already a scriptable fully-functional HTTP/HTTPS client, for implementing tests? I see a lot of re-inventing of the wheel here.

**Comment by dnorthup-ums** [comment]
(Why did commenting un-assign @dmogn ????)

**Comment by mzico** [comment]
@dnorthup-ums : Dmorgn doesn't work for Gluu anymore. May be we can assign this to Thomas? @willow9886
