### ISSUE TITLE
oxTrust need to display and log explicit warnings about email non-uniqueness

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#787]
Environment:
Ubuntu 14.04, gluu-server-3.1.1-1-8~trusty+Ub14.04

Preconditions:

1.  A valid xls file ready to be imported via oxTrust "Import People" feature, containing 5-10 people with unique usernames, but at least some of them containing non-unique emails (either the file itself contains duplicate email, or such email is already assigned to some user entry existing in Gluu's LDAP)

Steps to reproduce:

1. Log in to web UI as admin user.
2. Move to "Users -> Import People" page
3. Try to validate and import the xls file mentioned above
4. Move to "Users -> Add Person" page
5. Try to add a user with uid already assigned to another entry in LDAP tree, then try to add a user with unique uid, but with email attribute already assigned to existing entry.

Result:

At step 3) import fails and a misguiding error message is displayed, stating it's because of non-unique `uid` attributes, while in fact it's caused by non-unique `mail` attibutes. At step 5) for case when `uid` is not unique error message clearly states that, while when `mail` is not unique it just rejects to create user without giving a hint why. `oxtrust.log` is not very helpful either in those cases. The requirement for email to be unique is new feature of Gluu CE 3.x and wasn't present in 2.x packages, that's why oxTrust perhaps is not ready to handle it.

Expected result:

In both cases error messages must clearly state which of those 2 attributes is not unique (or at least mention that one of them or both are not unique, while they should be). It also would help with troubleshooting if a descriptive error message would start to be registered in `oxtrust.log`

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/33949483-bc592b6e-e04f-11e7-8f1a-e70631735674.png)

**Comment by shekhar16** [comment]
below screenshot for unique uid validation fail.
![image](https://user-images.githubusercontent.com/15937500/33950491-8f0f2002-e052-11e7-9c3c-cda3324b8448.png)

**Comment by tmburger** [comment]
I would add to this that a very similar issue occurs with cache refresh.  CR does not handle entries with non-unique values and instead dumps java exceptions to the oxtrust_cacherefreshlog.  If you look carefully you will see in the error that the reason is "Caused by: com.unbounded.ldap.sdk.LDAPException: some attributes not unique."  It would be very useful if a try/except block was used to catch these and to give a more specific error message in the log indicating which attribute was non-unique.  In my particular case I found the issue to be mail which is not unique in our AD, I imagine others will run into this problem as well and a clear log would go a long way for troubleshooting.

**Comment by mzico** [comment]
@tmburger : I agree; it's actually happening for OpenLDAP restriction.
@yurem : Do you think we can add more verbose log ( like which attribute is not unique etc. )

**Comment by willow9886** [comment]
@tmburger in Gluu 3.1.2 we are introducing the [clear log feature](https://github.com/GluuFederation/community-edition-package/issues/13) :)

**Comment by tmburger** [comment]
Seems like a nice feature but it does not resolve the issue that I was referring too.  What I actually meant was a "clean" log as in no java errors.  Because there are un-handled exceptions in the program, it is dumping java errors to the log instead of specific handled exception error messages.  For example.  Instead of 46 lines of failed java and python modules.  A simple message that says "The attribute (Blah) is not unique and needs to be"

Make sense?
I agree that being able to clear the logs on startup is a nice feature, I would even go so far as to say the "View log file" screen in the web interface should include the option to both clear the logs and configure log rotation but maybe I am asking for too much!

**Comment by willow9886** [comment]
Got it. @mzico feel free to open some issues on this for 3.1.3 or 3.2.0.

**Comment by mzico** [comment]
@willow9886 : https://github.com/GluuFederation/oxTrust/issues/813
