### ISSUE TITLE
SCIM API's to manage client specific pairwise identifiers

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#800]
For background, see OpenID Core Section 8.1 "Pairwise Identifier Algorithm"
  http://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg

For performance, it is desirable not to persist pairwise ids--this wastes both disk and compute.

Gluu supports both algorithmic and persistent identifiers, which is configured globally. The default is algorithmic. This screenshot shows the oxTrust view of the oxAuth JSON property: 

![config](https://user-images.githubusercontent.com/3717101/34447064-1233edb4-eca6-11e7-88f3-2deded622813.png)

In LDAP, client specific pairwise identifiers are stored as sub-tree under the person entry: `ou=pairwiseIdentifiers,inum=(person-inum),ou=people,o=(org-inum),o=gluu`

We need SCIM API's to enable clients to build tools to allow the user to view and remove this information.

**Comment by jgomer2001** [comment]
@nynymike 
Currently we have a simple way to do searches based on ppid through `/Users` endpoint.
It's based on the existence of `oxPPID` as a multi-valued attribute in `gluuPerson` objectclass. This attribute is added when the ppid + sectorIdentifier are persisted as a sub-entry under user branch: 
https://github.com/GluuFederation/oxAuth/blob/version_3.1.2/Server/src/main/java/org/xdi/oxauth/service/PairwiseIdentifierService.java#L97-L97

To offer a removal functionality from `/Users` endpoint we would have to clear `oxPPID` and also add special logic to remove the sub-entry... 

I don't like much going this way. Also, we should offer removal using `sector_identifier` as parameter too. So maybe we could add a new resource to SCIM for this? It might allow us to offer searching and deteting capabilities taking into account: userid, sub, and sector_identifier. But it's maybe too few added-value as to create a brand new resource?

In this thread there was a discussion where the idea of a new resource came up some time ago: https://github.com/GluuFederation/oxTrust/issues/364#issuecomment-251705016 

A side note is that `oxPPID` being part of user extension does not help much since we don't support complex custom attributes in the extension (e.g. we cannot have a cust attr composed of several attributes)

Another question could be: is this task related only to persistent pairwise ids? ... algorithmic strategy does not persist the value at all. Indeed, the computed value seems deterministic when the same (userinum, sector_uri) tuple is used - no apparently way to renew.

**Comment by jgomer2001** [comment]
I'll add a special  case in `/Users` endpoint to be able to remove this info according to our conversation.

In summary this attribute can only be queried and removed (not set or altered) via SCIM API.
