### ISSUE TITLE
Cache Refresh log improvement

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#813]
For v3 + OpenLDAP Cache Refresh operation, Gluu Server rejects entry if there is any duplicate attribute present in backend AD/LDAP. 

It will be nice if cache refresh log can specifically tell us 'which' attribute is duplicate ( most of the case.. it's email_address ). Right now here is how cache refresh log present such scenario which is not clear: 

```
Caused by: com.unbounded.ldap.sdk.LDAPException: some attributes not unique
```

**Comment by tmburger** [comment]
See attachment for exact error seen.
![notunique](https://user-images.githubusercontent.com/35322064/34845606-703e2f54-f6e3-11e7-98bf-80b50cf6ede6.jpg)

**Comment by yurem** [comment]
I've to close it with `wontfix` status because it's not Gluu software issue.

I tried to update one user entry to uid which exists in LDAP already:
```
dn: inum=2,ou=people,o=@!EC56.8FA2.3373.150C!0001!A186.329E,o=gluu
changetype: modify
replace: uid
uid: admin
```

After running ldapmodify I get in console:
```
Processing MODIFY request for inum=2,ou=people,o=@!EC56.8FA2.3373.150C!0001!A186.329E,o=gluu
MODIFY operation failed
Result Code:  19 (Constraint Violation)
Additional Information:  some attributes not unique
```

Also I get in /var/log/openldap/ldap.log:
```
Mar  9 15:38:47 u144 slapd[121541]: conn=1074 op=1 MOD dn="inum=2,ou=people,o=@!EC56.8FA2.3373.150C!0001!A186.329E,o=gluu"
Mar  9 15:38:47 u144 slapd[121541]: conn=1074 op=1 MOD attr=uid
Mar  9 15:38:47 u144 slapd[121541]: conn=1074 op=1 RESULT tag=103 err=19 duration=0.125ms text=some attributes not unique
```

As you can see OpenLDAP not provides detailed problem explanation. Hence Gluu can't get reasons of the issue. We can open OpenLdap issue for this. Here is why I think so.
