### ISSUE TITLE
Re-login instead of displaying oops Page

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#869]
When a Weld web session expires in oxTrust, and you click on something, it display an "Oops" error. It would be better if oxTrust did not display the page, and just automatically retries to refersh the session.

![image](https://user-images.githubusercontent.com/3717101/36695024-ac29238e-1b05-11e8-8031-bffcbb41cf17.png)

**Comment by yurem** [comment]
Implemented

**Comment by sahiliamsso** [comment]
Still able to see this error message on screen
![image](https://user-images.githubusercontent.com/21104811/38284065-0d5e2aa8-37d7-11e8-8935-ac001736d7f1.png)


Also, when you double click "Add Trust Relationship", you will see this screen appearing.

**Comment by yurem** [comment]
I've tried to reproduce it in latest beta build.
I did next:
1. Log into CE
2. Wait more than 30 minutes
3. Try to Open Groups list
4. As result oxTrust as expected send user to oxAuth login form and authenticate him without prompt because oxAuth session lifetime longer than 30 minutes by default.

Here is result and network communications:
![image](https://user-images.githubusercontent.com/6104200/38312189-bf9e6d2a-3829-11e8-9278-9a5ecf18684b.png)

Please re-open it if needed with list of steps how to reproduce it.
